spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${UPLOADER_DB_NAME}
    username: ${UPLOADER_DB_USER}
    password: ${UPLOADER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

filepasser:
  storage:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket-name: ${MINIO_BUCKET}
